### ISSUE TITLE
Do you have an example of how to set this up under Apache or Nginx?

### ISSUE THREAD

**Issue by EntropyWorks** [espebra/strapper#1]
I wanted to try this out and create the following strapper.wsgi file.

```
import sys, os
sys.path.insert (0,'/var/www/strapper')
os.chdir("/var/www/strapper")
from strapper import app as application
```

And for the apache config I added 

```
<virtualhost *:8080>

    ErrorLog ${APACHE_LOG_DIR}/strapper-error.log
    CustomLog ${APACHE_LOG_DIR}/strapper-access.log combined

    WSGIDaemonProcess strapper  user=www-data group=www-data threads=5 home=/var/www/strapper
    WSGIScriptAlias / /var/www/strapper/strapper.wsgi

    <directory /var/www/strapper>
        WSGIProcessGroup strapper
        #WSGIApplicationGroup %{GLOBAL}
        WSGIApplicationGroup %{ENV:REMOTE_ADDR}
        WSGIScriptReloading On
        Order deny,allow
        Allow from all
    </directory>
</virtualhost>
```
but when I go and try to add a mac address it fails.

```
curl http://strapper.example.com:8080/boot/aa:aa:aa:aa:aa:aa
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at picasso-seed.vse.rdlabs.hpecorp.net Port 8080</address>
</body></html>
```

In the apache error log.
```
 [remote XXX.XXX.XXX.XXX:43028] mod_wsgi (pid=12401): Exception occurred processing WSGI script '/var/www/strapper/strapper.wsgi'.
 [remote XXX.XXX.XXX.XXX:43028] Traceback (most recent call last):
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1518, in __call__
 [remote XXX.XXX.XXX.XXX:43028]     return self.wsgi_app(environ, start_response)
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1506, in wsgi_app
 [remote XXX.XXX.XXX.XXX:43028]     response = self.make_response(self.handle_exception(e))
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1504, in wsgi_app
 [remote XXX.XXX.XXX.XXX:43028]     response = self.full_dispatch_request()
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1264, in full_dispatch_request
 [remote XXX.XXX.XXX.XXX:43028]     rv = self.handle_user_exception(e)
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1262, in full_dispatch_request
 [remote XXX.XXX.XXX.XXX:43028]     rv = self.dispatch_request()
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/flask/app.py", line 1248, in dispatch_request
 [remote XXX.XXX.XXX.XXX:43028]     return self.view_functions[rule.endpoint](**req.view_args)
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/strapper.py", line 460, in boot
 [remote XXX.XXX.XXX.XXX:43028]     script = get_boot_script(mac)
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/strapper.py", line 211, in get_boot_script
 [remote XXX.XXX.XXX.XXX:43028]     data = read_data(mac)
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/strapper.py", line 161, in read_data
 [remote XXX.XXX.XXX.XXX:43028]     do_log("INFO","Discovered a new node with MAC %s" % (mac))
 [remote XXX.XXX.XXX.XXX:43028]   File "/var/www/strapper/strapper.py", line 391, in do_log
 [remote XXX.XXX.XXX.XXX:43028]     remote_addr = cgi.escape(os.environ['REMOTE_ADDR'])
 [remote XXX.XXX.XXX.XXX:43028]   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
 [remote XXX.XXX.XXX.XXX:43028]     raise KeyError(key)
 [remote XXX.XXX.XXX.XXX:43028] KeyError: 'REMOTE_ADDR'
```

I just can't seem to figure out how the 'REMOTE_ADDR' is set correctly.

**Comment by espebra** [comment]
Hi,

I've not used strapper for many years, and I don't have any example configuration. I recommend that you fork and look into the code if you're going to use it.

If you want an alternative, you may look into [Kickoff](https://github.com/espebra/kickoff). It is still being used in production by Redpill Linpro. On beforehand, I'm sorry for the lack of documentation.
